[device]
name = "Xiaomi Mi A2 Lite"
architecture = "aarch64"
flash_method = "fastboot-bootimg"

[boot]
cmdline = "quiet loglevel=2"
generate_bootimg = true

[boot.android]
base = "0x80000000"
page_size = 2048
kernel_offset = "0x00008000"
ramdisk_offset = "0x01000000"
second_offset = "0x00f00000"
tags_offset = "0x00000100"

[quirks]
keep_fb_refresher_with_dm = false
xorg_force_vt1 = true
